// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcthwdfogjedbcmubao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y3Rod2Rmb2dqZWRiY211YmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjEzODgsImV4cCI6MjA2Mzk5NzM4OH0.uRG_idkhJ9TfqOuA8jN9gWa9b6HJDx3nK0Rl2jjGWRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);